branch-defaults:
  aws-eb-master:
    environment: prod-2-10-1
  aws-eb-test:
    environment: test-2-11-1
    group_suffix: null
global:
  application_name: energy-sparks
  branch: null
  default_ec2_keyname: EnergySparksTestEC2
  default_platform: Ruby 2.5 (Puma)
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
