# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ab2fe0e211da787f17c1691aa39753ea90555dd1d99b27793ef30c9fd65663fda6f2292b1269695e1c4fff595c75b3631894ed1927c3926f2945e1bc896705b
  encrypted_field_salt: <%= ENV["ENCRYPTED_FIELD_SALT"] || "vinegar" %>

test:
  secret_key_base: e7ffd5428d507f6868edcc2ca43a53bcccef2db82840c88affdf4876bfc9468c6d95fc8a9f70f8c3ed95337d02cc98473056009b8e3aa1abbdb6ed2ff9f954b7
  encrypted_field_salt: 627e4bdbe8caa9c3e33234118886bed06354345798df9a59874bc10ca550ff62f9999ec03c81dd446542ddc3767b8d929b7e0ab62566d33a12a9e79b0988a9fb

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  encrypted_field_salt: <%= ENV["ENCRYPTED_FIELD_SALT"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  encrypted_field_salt: <%= ENV["ENCRYPTED_FIELD_SALT"] %>
